#ifndef IMAGENES_H
#define IMAGENES_H

// Nuevas dimensiones ampliadas para alta definición en bloques
const int FILAS = 40;
const int COLUMNAS = 40;

// Leyenda de caracteres:
// ' ' = Fondo Transparente / Blanco
// 'X' = Contornos, bordes y sombreados negros marcados
// '#' = Relleno de color principal (Sol=Amarillo, Oso=Marrón, Sal=Gris, Ala=Celeste, Ojo=Azul)

// --- ICONO: SOL (40x40) ---
const char* sol_map[FILAS] = {
  "                 XXXX                    ",
  "                 XXXX                    ",
  "             XXXX####XXXX                ",
  "             XXXX####XXXX                ",
  "         XXXX############XXXX            ",
  "         XXXX############XXXX            ",
  "     XXXX####################XXXX        ",
  "     XXXX####################XXXX        ",
  "   XX####XXXX############XXXX####XX      ",
  "   XX####XXXX############XXXX####XX      ",
  " XX########XXXX########XXXX########XX    ",
  " XX########XXXX########XXXX########XX    ",
  "XXXX###########XXXXXXXX###########XXXX  ",
  "XXXX###########XXXXXXXX###########XXXX  ",
  "XXXX#######XXXXXXXXXXXXXXXX#######XXXX  ",
  "XXXX#######XXXXXXXXXXXXXXXX#######XXXX  ",
  "  XX#####XXXXXXXXXXXXXXXXXXXX#####XX    ",
  "  XX#####XXXXXXXXXXXXXXXXXXXX#####XX    ",
  "XXXX####XXXXXXXXXXXXXXXXXXXXXX####XXXX  ",
  "XXXX####XXXXXXXXXXXXXXXXXXXXXX####XXXX  ",
  "XXXX####XXXXXXXXXXXXXXXXXXXXXX####XXXX  ",
  "XXXX####XXXXXXXXXXXXXXXXXXXXXX####XXXX  ",
  "  XX#####XXXXXXXXXXXXXXXXXXXX#####XX    ",
  "  XX#####XXXXXXXXXXXXXXXXXXXX#####XX    ",
  "XXXX#######XXXXXXXXXXXXXXXX#######XXXX  ",
  "XXXX#######XXXXXXXXXXXXXXXX#######XXXX  ",
  "XXXX###########XXXXXXXX###########XXXX  ",
  "XXXX###########XXXXXXXX###########XXXX  ",
  " XX########XXXX########XXXX########XX    ",
  " XX########XXXX########XXXX########XX    ",
  "   XX####XXXX############XXXX####XX      ",
  "   XX####XXXX############XXXX####XX      ",
  "     XXXX####################XXXX        ",
  "     XXXX####################XXXX        ",
  "         XXXX############XXXX            ",
  "         XXXX############XXXX            ",
  "             XXXX####XXXX                ",
  "             XXXX####XXXX                ",
  "                 XXXX                    ",
  "                 XXXX                    "
};

// --- ICONO: OSO (40x40) ---
const char* oso_map[FILAS] = {
  "      XXXXXX                XXXXXX      ",
  "    XX######XX            XX######XX    ",
  "   X##########X          X##########X   ",
  "   X##########X          X##########X   ",
  "   X####XX####X          X####XX####X   ",
  "    XX######XX            XX######XX    ",
  "      XXXXXX################XXXXXX      ",
  "          XX################XX          ",
  "        XX####################XX        ",
  "       X########################X       ",
  "      X##########################X      ",
  "     X############################X     ",
  "    X######XXXX##########XXXX######X    ",
  "    X######XXXX##########XXXX######X    ",
  "   X#######XXXX##########XXXX#######X   ",
  "   X################################X   ",
  "   X################################X   ",
  "   X################################X   ",
  "   X################################X   ",
  "   X#########XXXXXXXXXXXX#########X   ",
  "    X########XXXXXXXXXXXX########X    ",
  "    X##########XXXXXXXX##########X    ",
  "     X###########XXXX###########X     ",
  "     X##########################X     ",
  "      X########################X      ",
  "       X######################X       ",
  "        X####################X        ",
  "         X#####XXXXXXXX#####X         ",
  "          X####XXXXXXXX####X          ",
  "           X##############X           ",
  "            XX##########XX            ",
  "              XXXXXXXXXX              ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        "
};

// --- ICONO: SAL (40x40) ---
const char* sal_map[FILAS] = {
  "              XXXXXXXXXXXX              ",
  "            XX############XX            ",
  "           X################X           ",
  "           X################X           ",
  "           X####XXXXXXXX####X           ",
  "           X####XXXXXXXX####X           ",
  "           X################X           ",
  "           X################X           ",
  "          XXXXXXXXXXXXXXXXXXXX          ",
  "         X####################X         ",
  "        X######################X        ",
  "       X########################X       ",
  "      X##########################X      ",
  "     X############################X     ",
  "     X######XX############XX######X     ",
  "     X######XX############XX######X     ",
  "     X############################X     ",
  "     X############################X     ",
  "     X######XX############XX######X     ",
  "     X######XX############XX######X     ",
  "     X############################X     ",
  "     X############################X     ",
  "     X######XX############XX######X     ",
  "     X######XX############XX######X     ",
  "     X############################X     ",
  "     X############################X     ",
  "     X######XX############XX######X     ",
  "     X######XX############XX######X     ",
  "     X############################X     ",
  "     X############################X     ",
  "     X############################X     ",
  "      X##########################X      ",
  "       X########################X       ",
  "        X######################X        ",
  "         X####################X         ",
  "          XXXXXXXXXXXXXXXXXXXX          ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        "
};

// --- ICONO: ALA (40x40) ---
const char* ala_map[FILAS] = {
  "  XXXXXXXXXXXXXXXXXXXXXXXX              ",
  " X########################XXXX          ",
  " X############################XXXX      ",
  " X################################XXXX  ",
  "  X###################################X ",
  "   X############XXXXXXXXXXXXXXXXXXXXXX  ",
  "    X###########X                       ",
  "     X##########X                       ",
  "  XXXX##########XXXXXXXXXXXXXXXXXXXX    ",
  " X##################################XX  ",
  " X####################################X ",
  "  X#############XXXXXXXXXXXXXXXXXXXXXX  ",
  "   X############X                       ",
  "    X###########X                       ",
  "  XXX###########XXXXXXXXXXXXXXXXXX      ",
  " X################################XX    ",
  " X##################################X   ",
  "  X#############XXXXXXXXXXXXXXXXXXXX    ",
  "   X############X                       ",
  "    X###########X                       ",
  "  XXX###########XXXXXXXXXXXXXX          ",
  " X############################XX        ",
  " X##############################X       ",
  "  X#############XXXXXXXXXXXXXXXX        ",
  "   X############X                       ",
  "    X###########X                       ",
  "     X##########XXXXXXXXXXXX            ",
  "      X#####################XX          ",
  "       X######################X         ",
  "        XXXXXXXXXXXX###########X        ",
  "                    X##########X        ",
  "                     X#########X        ",
  "                      X########X        ",
  "                       X#######X        ",
  "                        X######X        ",
  "                         X#####X        ",
  "                          X####X        ",
  "                           XXXX         ",
  "                                        ",
  "                                        "
};

// --- ICONO: OJO (40x40) ---
const char* ojo_map[FILAS] = {
  "                                        ",
  "              XXXXXXXXXXXX              ",
  "          XXXX############XXXX          ",
  "        XX####################XX        ",
  "      XX########################XX      ",
  "     X############################X     ",
  "    X##############################X    ",
  "   X##########XXXXXXXX##########    X   ",
  "  X#########XX########XX#########    X  ",
  " X########XX############XX########    X ",
  " X#######XX##############XX#######    X ",
  "X#######X######XXXX######X#######X    X",
  "X#######X####XXXXXXXX####X#######X     ",
  "X######X####XXXXXXXXXX####X######X     ",
  "X######X####XXXXXXXXXX####X######X     ",
  "X######X####XXXXXXXXXX####X######X     ",
  "X######X####XXXXXXXXXX####X######X     ",
  "X######X####XXXXXXXXXX####X######X     ",
  "X#######X####XXXXXXXX####X#######X     ",
  "X#######X######XXXX######X#######X    X",
  " X#######XX##############XX#######    X ",
  " X########XX############XX########    X ",
  "  X#########XX########XX#########    X  ",
  "   X##########XXXXXXXX##########    X   ",
  "    X##############################X    ",
  "     X############################X     ",
  "      XX########################XX      ",
  "        XX####################XX        ",
  "          XXXX############XXXX          ",
  "              XXXXXXXXXXXX              ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        ",
  "                                        "
};

#endif